### ISSUE TITLE
condense_intsites fails on empty GRanges object

### ISSUE THREAD

**Issue by kevinmcc21** [cnobles/gintools#11]
This error occurred for me in the CHIVA pipeline.  Specifically on the line:
  sites.to.condense$group.id <- paste0(group, "^", sites.to.condense$posid)
Error in `[[<-`(`*tmp*`, name, value = "^") : 
  1 elements in value to replace 0 elements

**Comment by cnobles** [comment]
Removing the delimiter "^" resolves the issue. Additionally, a fix was managed in determine_abundance which also error'ed out with a zero length input. Updates included in commit a7530e687ec68224f32d80ee9bb30a337200469b.
